[settings]
experimental = true # Required to use lockfile.
lockfile = true     # DO NOT FORGET TO `touch mise.lock`!

[tools]
go = "latest"
# gorun: improved `go run`
"go:github.com/erning/gorun" = "latest"
# yq: jq for yaml
yq = "latest"
# jv: json schema validator for yaml
"ubi:santhosh-tekuri/jsonschema" = { version = "latest", exe = "jv" }

[tasks.convert]
description = "Convert all versions"
depends = ['convert/*']

# When we'll have a lot of these we can replace them all with a task-to-generate-tasks. :-D
[tasks."convert/1.60.3"]
sources = ['1.60.3/reference/.golangci.yml']
outputs = ['1.60.3/.golangci.yml']
run = 'GOWORK="$PWD/scripts/go.work" gorun ./scripts/convert 1.60.3 1.60'
# run = 'scripts/convert.sh 1.60.3 1.60'

[tasks."convert/1.61.0"]
sources = ['1.61.0/reference/.golangci.yml']
outputs = ['1.61.0/.golangci.yml']
run = 'GOWORK="$PWD/scripts/go.work" gorun ./scripts/convert 1.61.0 1.60'

[tasks."convert/1.62.0"]
sources = ['1.62.0/reference/.golangci.yml']
outputs = ['1.62.0/.golangci.yml']
run = 'GOWORK="$PWD/scripts/go.work" gorun ./scripts/convert 1.62.0 1.62'

[tasks."convert/1.64.8"]
sources = ['1.64.8/reference/.golangci.yml']
outputs = ['1.64.8/.golangci.yml']
run = 'GOWORK="$PWD/scripts/go.work" gorun ./scripts/convert 1.64.8 1.64'

[tasks."convert/2.1.6"]
sources = ['2.1.6/reference/.golangci.yml']
outputs = ['2.1.6/.golangci.yml']
run = 'GOWORK="$PWD/scripts/go.work" gorun ./scripts/convert 2.1.6 2.1.6'

[tasks."convert/2.2.1"]
sources = ['2.2.1/reference/.golangci.yml']
outputs = ['2.2.1/.golangci.yml']
run = 'GOWORK="$PWD/scripts/go.work" gorun ./scripts/convert 2.2.1 2.1.6'
